# Generated by Django 2.2.1 on 2019-05-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access',
            field=models.CharField(choices=[('standart', 'standart'), ('moderator', 'moderator'), ('admin', 'admin')],
                                   default='standart', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
