# Generated by Django 2.2.2 on 2019-06-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190613_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access',
            field=models.CharField(choices=[('Пользователь', 'Пользователь'), ('Модератор', 'Модератор'), ('Администратор', 'Администратор')], default='standart', max_length=20),
        ),
    ]
