# Generated by Django 2.2.2 on 2019-06-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190614_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='journal',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
